name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku #set whatever name you want here
        if: ${{ github.event_name == 'push' }}
        id: heroku
        uses: jctaveras/heroku-deploy@66bad8e81927dbf4a39ef8364a4c2f3043233ce0
        with:
          email: "codebook.ng@gmail.com"
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_path: "docker/dev/go"
