name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  docker_image_deployment:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Build, Push and Deploy to Heroku
        if: ${{ github.event_name == 'push' }}
        id: heroku
        # uses: jctaveras/heroku-deploy@66bad8e81927dbf4a39ef8364a4c2f3043233ce0
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: "codebook.ng@gmail.com"
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          # dockerfile_path: "docker/dev/go"
          dockerfile_directory: "docker/dev/go"
